name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC 0:00自动同步，可根据需要更改cron表达式
jobs:
  sync:
    runs-on: ubuntu - latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/LibreSpark/LibreTV.git || true
          git fetch upstream
          git merge upstream/main # 若不是main分支，改为相应分支名
          git push origin main # 若不是main分支，改为相应分支名
